stages:
  - build

build:
  stage: build
  image: node
  cache:
    paths:
      - node_modules/
    untracked: true
  script:
    - npm install
    - npm run test
    - npm install --global gulp-cli
    - gulp init
    - gulp texts
  artifacts:
    paths:
      - dist
    expire_in: 1 day
